# Cấu hình kết nối Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/street_voice_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình JPA/Hibernate
# Tự động update schema database dựa trên Entity
spring.jpa.hibernate.ddl-auto=update
# Hiển thị câu lệnh SQL trong console (để debug)
spring.jpa.show-sql=true
# Format SQL cho dễ đọc
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình Server
server.address=0.0.0.0
server.port=8080

# Cấu hình Flyway
spring.flyway.clean-on-validation-error=false
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false

app.auth.jwt-secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970


app.audio.local-path=uploads/audio
app.audio.base-url=http://localhost:8080